version: '3.8'

services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: simpulse-benchmark
    volumes:
      - ./results:/benchmark/results
      
  validation:
    build:
      context: .
      dockerfile: Dockerfile.validation
    container_name: simpulse-validation
    volumes:
      - ./validation_results:/validation/validation_results
    stdin_open: true
    tty: true