-- Auto-generated by Simpulse JIT Optimizer
import Lean

namespace Simpulse.JIT

-- Priority configuration from runtime profiling
def optimizedPriorities : List (Name × Nat) := [  (`List.append_nil, 100),
  (`Nat.add_zero, 110),
  (`Nat.zero_add, 120),
  (`List.nil_append, 130),
  (`List.map_append, 140)
]

-- Apply optimized priorities at initialization
def applyOptimizedPriorities : IO Unit := do
  for (rule, priority) in optimizedPriorities do
    -- Set simp priority for rule
    modifyEnv fun env => 
      simpExtension.modifyState env fun s =>
        s.insert rule priority

-- Initialize on import
initialize applyOptimizedPriorities

end Simpulse.JIT
