[tool.poetry]
name = "simpulse"
version = "1.1.0"
description = "High-performance optimization tool for Lean 4 simp tactics"
authors = ["Bright Liu <bright.liu@example.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Bright-L01/simpulse"
documentation = "https://simpulse.readthedocs.io"
keywords = ["lean4", "theorem-proving", "optimization", "simp", "tactics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Compilers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Environment :: Console",
]
packages = [{include = "simpulse", from = "src"}]

[tool.poetry.scripts]
simpulse = "simpulse.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
rich = "^13.7.0"
pydantic = "^2.5.0"
typing-extensions = "^4.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
mypy = "^1.7.1"
ruff = "^0.1.6"
bandit = {extras = ["toml"], version = "^1.7.5"}
black = "^23.11.0"
isort = "^5.12.0"
pre-commit = "^3.5.0"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
mkdocs-material = "^9.4.14"
mkdocstrings = {extras = ["python"], version = "^0.24.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.black]
line-length = 100
target-version = ['py310']

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-ra",
    "--strict-markers",
    "--cov=simpulse",
    "--cov-report=term-missing",
    "--cov-fail-under=85",
]
testpaths = ["tests"]