[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simpulse"
version = "0.1.0"
description = "AlphaEvolve-style Simp Rule Optimizer for Lean 4"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "click>=8.0",
    "anthropic>=0.18.0",
    "pandas>=2.0",
    "numpy>=1.24",
    "pyyaml>=6.0",
    "rich>=13.0",
    "asyncio>=3.4",
    "aiofiles>=23.0",
    "matplotlib>=3.7",
    "seaborn>=0.12",
    "pytest>=7.0",
    "pytest-asyncio>=0.21",
]

[project.optional-dependencies]
dev = [
    "black>=23.0",
    "isort>=5.12",
    "mypy>=1.0",
    "ruff>=0.1",
    "pre-commit>=3.0",
]

[project.scripts]
simpulse = "simpulse.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88
