-- Basic arithmetic simplifications
namespace Basic

@[simp] theorem add_zero_0 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_0 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_0 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_1 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_1 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_1 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_2 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_2 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_2 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_3 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_3 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_3 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_4 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_4 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_4 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_5 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_5 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_5 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_6 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_6 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_6 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_7 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_7 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_7 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_8 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_8 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_8 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_9 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_9 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_9 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_10 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_10 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_10 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_11 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_11 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_11 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_12 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_12 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_12 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_13 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_13 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_13 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_14 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_14 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_14 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_15 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_15 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_15 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_16 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_16 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_16 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_17 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_17 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_17 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_18 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_18 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_18 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_19 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_19 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_19 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_20 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_20 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_20 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_21 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_21 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_21 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_22 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_22 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_22 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_23 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_23 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_23 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_24 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_24 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_24 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_25 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_25 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_25 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_26 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_26 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_26 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_27 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_27 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_27 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_28 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_28 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_28 (n : Nat) : n * 1 = n := Nat.mul_one n
@[simp] theorem add_zero_29 (n : Nat) : n + 0 = n := Nat.add_zero n
@[simp] theorem zero_add_29 (n : Nat) : 0 + n = n := Nat.zero_add n
@[simp] theorem mul_one_29 (n : Nat) : n * 1 = n := Nat.mul_one n

end Basic
