name: CI Fixed

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true
        
    - name: Install dependencies
      run: |
        poetry install --with dev
        
    - name: Code formatting check
      run: |
        poetry run black --check src/ tests/
        poetry run isort --check-only src/ tests/
        
    - name: Linting
      run: poetry run ruff check src/ tests/
      
    - name: Type checking
      run: poetry run mypy src/

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: quality
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.in-project true
        
    - name: Install dependencies
      run: poetry install --with dev
      
    - name: Run tests
      run: |
        poetry run pytest tests/test_core.py tests/test_simple_optimizer.py -v
        
    - name: Test CLI
      run: |
        poetry run simpulse --version
        poetry run simpulse --help

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Build package
      run: poetry build
      
    - name: Check package
      run: |
        pip install twine
        twine check dist/*