name: 'Optimize Simp Rules'

on:
  # Weekly optimization on Sunday at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      modules:
        description: 'Modules to optimize (comma-separated or "auto")'
        required: false
        default: 'auto'
      time_budget:
        description: 'Time budget in seconds'
        required: false
        default: '7200'
      target_improvement:
        description: 'Target improvement percentage'
        required: false
        default: '15'
      create_pr:
        description: 'Create pull request'
        type: boolean
        required: false
        default: true

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Run Simpulse Optimization
      id: simpulse
      uses: ./.github/actions/simpulse
      with:
        modules: ${{ github.event.inputs.modules || 'auto' }}
        time-budget: ${{ github.event.inputs.time_budget || '7200' }}
        target-improvement: ${{ github.event.inputs.target_improvement || '15' }}
        population-size: '30'
        max-generations: '50'
        create-pr: ${{ github.event.inputs.create_pr || 'true' }}
        pr-branch: 'simpulse/optimize-${{ github.run_number }}'
        base-branch: 'main'
        cache-enabled: 'true'
        progress-comments: 'true'
        report-format: 'both'
        parallel-workers: '4'
        enable-telemetry: 'true'
        dry-run: 'false'
    
    - name: Upload optimization report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simpulse-optimization-report
        path: |
          /app/reports/optimization_report.html
          /app/reports/optimization_report.md
          /app/reports/results.json
        retention-days: 30
    
    - name: Comment on success
      if: steps.simpulse.outputs.success == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const improvement = '${{ steps.simpulse.outputs.improvement-percent }}';
          const generations = '${{ steps.simpulse.outputs.total-generations }}';
          const execTime = '${{ steps.simpulse.outputs.execution-time }}';
          const mutations = '${{ steps.simpulse.outputs.mutations-applied }}';
          const prUrl = '${{ steps.simpulse.outputs.pr-url }}';
          
          let body = `## 🎉 Simpulse Optimization Completed Successfully!
          
          **Results:**
          - 📈 **Improvement**: ${improvement}%
          - 🧬 **Generations**: ${generations}
          - ⏱️ **Execution Time**: ${execTime}s
          - 🔧 **Mutations Applied**: ${mutations}
          `;
          
          if (prUrl) {
            body += `\n**Pull Request**: ${prUrl}`;
          }
          
          body += `\n\n*Optimization completed on ${new Date().toISOString()}*`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Simpulse Optimization Results - ${improvement}% improvement`,
            body: body,
            labels: ['simpulse', 'optimization', 'automated']
          });
    
    - name: Comment on failure
      if: steps.simpulse.outputs.success != 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const execTime = '${{ steps.simpulse.outputs.execution-time }}';
          
          const body = `## ❌ Simpulse Optimization Failed
          
          The automated simp rule optimization failed to complete successfully.
          
          **Details:**
          - ⏱️ **Execution Time**: ${execTime}s
          - 🔍 **Check**: Review the workflow logs for detailed error information
          
          *Failed on ${new Date().toISOString()}*`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Simpulse Optimization Failed',
            body: body,
            labels: ['simpulse', 'failure', 'automated']
          });